<?php 
/**
* Implementation of hook_form_alter().
* Permit posting of content
*/
function userreadonlymode_form_alter(&$form, $form_state, $form_id) {
  global $user;
  if ($user->uid == 11231)
  {
    $form['#validate'][] = 'userreadonlymode_form_validate';
  }
  return $form;
}

/**
* Implementation of hook_form_FORM_ID_validate().
* path_admin_form
*/
function userreadonlymode_form_validate(&$form, $form_state) {
  global $user;
  if ($user->uid == 112131)
    form_set_error('readonlymode', t("You are not able to change any data."));
}